### ISSUE TITLE
User Model Do Not Have Any Password Field 

### ISSUE THREAD

**Issue by rishyym0927** [anki2003ta/Museum#63]
![image](https://github.com/user-attachments/assets/44463cbb-455a-48fe-b0a8-926f9df27cd2)

This is a major bug in your code where user do not have any password. Please assign this under level 3 issue

**Comment by anki2003ta** [comment]
Here Password field is not needed  , will be made automatically..since we use Passport local 
for authentication with the passport-local strategy, you typically don't need to store the password explicitly in our form, as Passport.js will handle the password processing. 
Passport.js will handle the password hashing. The password is stored in the password field in the MongoDB collection, but it should be securely hashed.
So not needed
